export const SELECTOR_PRACTICE_FORM = {
    firstName: "#firstName",
    lastName: "#lastName",
    userEmail: "#userEmail",
    maleRadioButton: "#gender-radio-1",
    femaleRadioButton: "#gender-radio-2",
    otherRadioButton: "#gender-radio-3",
    userNumber: "#userNumber",
    dateOfBirthInput: "#dateOfBirthInput",
    dateOfBirthYearPicker: ".react-datepicker__year-select",
    dateOfBirthMonthPicker: ".react-datepicker__month-select",
    dateOfBirthWeekPicker: ".react-datepicker__week",
    subjectsContainer: "#subjectsContainer",
    subjectItem: ".subjects-auto-complete__multi-value__label",
    sportsCheckbox: "#hobbies-checkbox-1",
    readingCheckbox: "#hobbies-checkbox-2",
    musicCheckbox: "#hobbies-checkbox-3",
    uploadPicture: "#uploadPicture",
    currentAddress: "#currentAddress",
    stateDropdown: "#state",
    stateContainer: "#state [class$='singleValue']",
    cityDropdown: "#city",
    cityContainer: "#city [class$='singleValue']",
    cityInput: "#city #react-select-4-input",
    submitButton: "#submit",
    welcomeModal: "#example-modal-sizes-title-lg",
    userNameValue: "tr:nth-child(1) td:nth-child(2)",
    userEmailValue:"tr:nth-child(2) td:nth-child(2)",
    userGenderValue:"tr:nth-child(3) td:nth-child(2)",
    userNumberValue:"tr:nth-child(4) td:nth-child(2)",
    userdateOfBirthValue:"tr:nth-child(5) td:nth-child(2)",
    subjectValue:"tr:nth-child(6) td:nth-child(2)",
    hobbieValue:"tr:nth-child(7) td:nth-child(2)",
    pictureValue:"tr:nth-child(8) td:nth-child(2)",
    currentAddressValue:"tr:nth-child(9) td:nth-child(2)",
    stateAndCityValue:"tr:nth-child(10) td:nth-child(2)"
}