export const SELECTOR_TABLES = {
    addButton: "#addNewRecordButton",
    optionModal: ".modal-content",
    firstName: "#firstName",
    lastName: "#lastName",
    userEmail: "#userEmail",
    userAge: "#age",
    salary: "#salary",
    department: "#department",
    submit: "#submit",
    table: ".rt-tbody",
    editFourthRecord: "#edit-record-4",
    deleteFirstRecord : "#delete-record-1",
    firstRow: ".rt-table .rt-tr-group:first-child .rt-tr .rt-td",
    searchBox: "#searchBox",
    rowSelect: "[aria-label='rows per page']",
    eachRow: ".rt-tr-group",
    columnSortingButton: ".rt-resizable-header-content",
    orderAscPointer: ".rt-tr>.rt-th.rt-resizable-header.-sort-asc.-cursor-pointer",
    orderDescPointer: ".rt-tr>.rt-th.rt-resizable-header.-sort-desc.-cursor-pointer",
    firstNameColumn: ".rt-td:first-child",
    lastNameColumn: ".rt-td:nth-child(2)",
    ageColumn: ".rt-td:nth-child(3)",
    emailColumn: ".rt-td:nth-child(4)",
    salaryColumn: ".rt-td:nth-child(5)",
    departmentColumn: ".rt-td:nth-child(6)",
}